// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdVoRjQNK6NOCTKyfk52gwX8zA1SPUalA',
    appId: '1:235362070271:web:43340544601d4b4198a6ca',
    messagingSenderId: '235362070271',
    projectId: 'atvauladia7do10',
    authDomain: 'atvauladia7do10.firebaseapp.com',
    storageBucket: 'atvauladia7do10.firebasestorage.app',
    measurementId: 'G-XP7G5HRPV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-3pDqsXlnoIYwmwI07JriuKXBZgBo0Xg',
    appId: '1:235362070271:android:38a8334dd97ad92098a6ca',
    messagingSenderId: '235362070271',
    projectId: 'atvauladia7do10',
    storageBucket: 'atvauladia7do10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHjNF-Er6Zasb7AHaOmxBV9ZtUGsQOJIY',
    appId: '1:235362070271:ios:f92675cd5cceabfc98a6ca',
    messagingSenderId: '235362070271',
    projectId: 'atvauladia7do10',
    storageBucket: 'atvauladia7do10.firebasestorage.app',
    iosClientId: '235362070271-hq14q7860ceuea5pe2kj69fc5uaibl6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHjNF-Er6Zasb7AHaOmxBV9ZtUGsQOJIY',
    appId: '1:235362070271:ios:f92675cd5cceabfc98a6ca',
    messagingSenderId: '235362070271',
    projectId: 'atvauladia7do10',
    storageBucket: 'atvauladia7do10.firebasestorage.app',
    iosClientId: '235362070271-hq14q7860ceuea5pe2kj69fc5uaibl6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdVoRjQNK6NOCTKyfk52gwX8zA1SPUalA',
    appId: '1:235362070271:web:1dad1038a2b5660f98a6ca',
    messagingSenderId: '235362070271',
    projectId: 'atvauladia7do10',
    authDomain: 'atvauladia7do10.firebaseapp.com',
    storageBucket: 'atvauladia7do10.firebasestorage.app',
    measurementId: 'G-2P1WNF2LKF',
  );
}
